"""Add phone verification fields and update subscription types

Revision ID: 60a87dae919f
Revises: 90c55204a630
Create Date: 2025-04-28 15:10:07.559343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60a87dae919f'
down_revision: Union[str, None] = '90c55204a630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_phone_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone_verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_verification_expiry', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_verification_expiry')
    op.drop_column('users', 'phone_verification_code')
    op.drop_column('users', 'is_phone_verified')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
