"""Add user profiles table

Revision ID: 78c43957d4fb
Revises: 69044f0bef15
Create Date: 2025-04-09 03:53:26.368111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c43957d4fb'
down_revision: Union[str, None] = '69044f0bef15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('brand_info', sa.JSON(), nullable=True))
    op.execute('ALTER TABLE user_profiles ALTER COLUMN skin_concerns TYPE JSON USING skin_concerns::json')
    op.execute('ALTER TABLE user_profiles ALTER COLUMN sensitivities TYPE JSON USING sensitivities::json')
    op.execute('ALTER TABLE user_profiles ALTER COLUMN hair_concerns TYPE JSON USING hair_concerns::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'hair_concerns',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'sensitivities',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'skin_concerns',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('user_profiles', 'brand_info')
    # ### end Alembic commands ###
