"""Add hair profile fields to user_profiles

Revision ID: 90c55204a630
Revises: cf2b83b311e7
Create Date: 2025-04-11 01:01:24.912732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c55204a630'
down_revision: Union[str, None] = 'cf2b83b311e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('brand_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'brand_info')
    # ### end Alembic commands ###
