"""add_cost_management_fields

Revision ID: bcd2a962e46d
Revises: 69c810976ed7
Create Date: 2025-06-11 03:30:00.205458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd2a962e46d'
down_revision: Union[str, None] = '69c810976ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulas', sa.Column('batch_size', sa.Float(), nullable=True))
    op.add_column('formulas', sa.Column('batch_unit', sa.String(), nullable=True))
    op.add_column('ingredients', sa.Column('cost_per_gram', sa.Float(), nullable=True))
    op.add_column('ingredients', sa.Column('cost_per_oz', sa.Float(), nullable=True))
    op.add_column('ingredients', sa.Column('purchase_cost', sa.Float(), nullable=True))
    op.add_column('ingredients', sa.Column('purchase_quantity', sa.Float(), nullable=True))
    op.add_column('ingredients', sa.Column('purchase_unit', sa.String(), nullable=True))
    op.add_column('ingredients', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('ingredients', sa.Column('supplier_name', sa.String(), nullable=True))
    op.add_column('ingredients', sa.Column('supplier_sku', sa.String(), nullable=True))
    op.add_column('ingredients', sa.Column('last_updated_cost', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ingredients', sa.Column('shipping_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'shipping_cost')
    op.drop_column('ingredients', 'last_updated_cost')
    op.drop_column('ingredients', 'supplier_sku')
    op.drop_column('ingredients', 'supplier_name')
    op.drop_column('ingredients', 'currency')
    op.drop_column('ingredients', 'purchase_unit')
    op.drop_column('ingredients', 'purchase_quantity')
    op.drop_column('ingredients', 'purchase_cost')
    op.drop_column('ingredients', 'cost_per_oz')
    op.drop_column('ingredients', 'cost_per_gram')
    op.drop_column('formulas', 'batch_unit')
    op.drop_column('formulas', 'batch_size')
    # ### end Alembic commands ###
