"""Add hair profile fields to user_profiles

Revision ID: cf2b83b311e7
Revises: fdbc8253f65e
Create Date: 2025-04-11 00:46:50.254397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf2b83b311e7'
down_revision: Union[str, None] = 'fdbc8253f65e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('hair_type', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('hair_concerns', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'hair_concerns')
    op.drop_column('user_profiles', 'hair_type')
    # ### end Alembic commands ###
